import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Home from './Home/home';
import './globals.css'
import { Disclosure } from '@headlessui/react';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout(){
  return (
    <Home/>
  );
  
}
