<<<<<<< HEAD
// "use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
=======
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Example from "./Home/Header";
>>>>>>> 1709d3dedf9cdbc243fbb830564ef746bf574347
// import Home from "./Home/home";
import "./styles/globals.css";
import { Disclosure } from "@headlessui/react";
import Link from "next/link";
import Example from "./Home/Header";
// import { Dropdown } from "flowbite";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children, // will be a page or nested layout
}: {
  children: React.ReactNode;
}) {
  return (
    <section className="flex flex-col min-h-screen">
<<<<<<< HEAD
      
      <Example/>
=======
      <Example />
>>>>>>> 1709d3dedf9cdbc243fbb830564ef746bf574347

      {children}
    </section>
  );
}
